<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
    <meta charset="utf-8">
    <meta name="generator" content="quarto-1.10.3">

    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


    <title>Supplementary Material S1: Expanded descriptions of the food web reconstruction approaches</title>
    <style>
      /* Default styles provided by pandoc.
      ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
      */
      code{white-space: pre-wrap;}
      span.smallcaps{font-variant: small-caps;}
      div.columns{display: flex; gap: min(4vw, 1.5em);}
      div.column{flex: auto; overflow-x: auto;}
      div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
      ul.task-list{list-style: none;}
      ul.task-list li input[type="checkbox"] {
        width: 0.8em;
        margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
        vertical-align: middle;
      }
      /* CSS for citations */
      div.csl-bib-body { }
      div.csl-entry {
        clear: both;
      }
      .hanging-indent div.csl-entry {
        margin-left:2em;
        text-indent:-2em;
      }
      div.csl-left-margin {
        min-width:2em;
        float:left;
      }
      div.csl-right-inline {
        margin-left:2em;
        padding-left:1em;
      }
      div.csl-indent {
        margin-left: 2em;
      }    </style>

    <style>
      body.hypothesis-enabled #quarto-embed-header {
        padding-right: 36px;
      }

      #quarto-embed-header {
        height: 3em;
        width: 100%;
        display: flex;
        justify-content: space-between;
        align-items: center;
        border-bottom: solid 1px;
      }

      #quarto-embed-header h6 {
        font-size: 1.1em;
        padding-top: 0.6em;
        margin-left: 1em;
        margin-right: 1em;
        font-weight: 400;
      }

      #quarto-embed-header a.quarto-back-link,
      #quarto-embed-header a.quarto-download-embed {
        font-size: 0.8em;
        margin-top: 1em;
        margin-bottom: 1em;
        margin-left: 1em;
        margin-right: 1em;
      }

      .quarto-back-container {
        padding-left: 0.5em;
        display: flex;
      }

      .headroom {
          will-change: transform;
          transition: transform 200ms linear;
      }

      .headroom--pinned {
          transform: translateY(0%);
      }

      .headroom--unpinned {
          transform: translateY(-100%);
      }      
    </style>

    <script>
    window.document.addEventListener("DOMContentLoaded", function () {

      var header = window.document.querySelector("#quarto-embed-header");
      const titleBannerEl = window.document.querySelector("body > #title-block-header");
      if (titleBannerEl) {
        titleBannerEl.style.paddingTop = header.clientHeight + "px";
      }
      const contentEl = window.document.getElementById('quarto-content');
      for (const child of contentEl.children) {
        child.style.paddingTop = header.clientHeight + "px";
        child.style.marginTop = "1em";
      }

      // Use the article root if the `back` call doesn't work. This isn't perfect
      // but should typically work
      window.quartoBackToArticle = () => {
        var currentUrl = window.location.href;
        window.history.back();
        setTimeout(() => {
            // if location was not changed in 100 ms, then there is no history back
            if(currentUrl === window.location.href){              
                // redirect to site root
                window.location.href = "../index.html";
            }
        }, 100);
      }

      const headroom = new window.Headroom(header, {
        tolerance: 5,
        onPin: function () {
        },
        onUnpin: function () {
        },
      });
      headroom.init();
    });
    </script>

    
<script src="../site_libs/manuscript-notebook/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-e44360b8a8db1e130c7792fece1c8032.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-3b1896eddc8589bc6244f4e1c31347fc.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="../site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="../site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="../site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
     <script async="" src="https://hypothes.is/embed.js"></script>
<script>
  window.document.addEventListener("DOMContentLoaded", function (_event) {
    document.body.classList.add('hypothesis-enabled');
  });
</script>   <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script> 
      </head>

  <body class="quarto-notebook quarto-light">
    <div id="quarto-embed-header" class="headroom fixed-top bg-primary">
      
      <a onclick="window.quartoBackToArticle(); return false;" class="btn btn-primary quarto-back-link" href=""><i class="bi bi-caret-left"></i> Back to Article</a>
      <h6><i class="bi bi-journal-code"></i> Supplementary Material S1: Expanded descriptions of the food web reconstruction approaches</h6>

            <a href="../notebooks/model_summaries.qmd" class="btn btn-primary quarto-download-embed" download="model_summaries.qmd">Download Source</a>
          </div>

     <header id="title-block-header" class="quarto-title-block default toc-left page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Supplementary Material S1: Expanded descriptions of the food web reconstruction approaches</h1>
          </div>

    
    <div class="quarto-title-meta-container">
      <div class="quarto-title-meta-column-start">
        
        <div class="quarto-title-meta">

                
          
                
              </div>
      </div>
      <div class="quarto-title-meta-column-end quarto-other-formats-target">
      </div>
    </div>



    <div class="quarto-other-links-text-target">
    </div>  </div>
</header><div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#model-descriptions" id="toc-model-descriptions" class="nav-link active" data-scroll-target="#model-descriptions">Model descriptions</a>
  <ul class="collapse">
  <li><a href="#structural-models" id="toc-structural-models" class="nav-link" data-scroll-target="#structural-models">Structural models</a>
  <ul class="collapse">
  <li><a href="#random-model" id="toc-random-model" class="nav-link" data-scroll-target="#random-model">Random model</a></li>
  <li><a href="#niche-model" id="toc-niche-model" class="nav-link" data-scroll-target="#niche-model">Niche model</a></li>
  </ul></li>
  <li><a href="#realised-models" id="toc-realised-models" class="nav-link" data-scroll-target="#realised-models">Realised models</a>
  <ul class="collapse">
  <li><a href="#allometric-diet-breadth-model" id="toc-allometric-diet-breadth-model" class="nav-link" data-scroll-target="#allometric-diet-breadth-model">Allometric diet breadth model</a></li>
  <li><a href="#allometric-trophic-network-model" id="toc-allometric-trophic-network-model" class="nav-link" data-scroll-target="#allometric-trophic-network-model">Allometric trophic network model</a></li>
  <li><a href="#body-size-ratio-model" id="toc-body-size-ratio-model" class="nav-link" data-scroll-target="#body-size-ratio-model">Body size ratio model</a></li>
  </ul></li>
  <li><a href="#feasibility-models" id="toc-feasibility-models" class="nav-link" data-scroll-target="#feasibility-models">Feasibility models</a>
  <ul class="collapse">
  <li><a href="#paleo-food-web-inference-model" id="toc-paleo-food-web-inference-model" class="nav-link" data-scroll-target="#paleo-food-web-inference-model">Paleo food web inference model</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#network-construction" id="toc-network-construction" class="nav-link" data-scroll-target="#network-construction">Network construction</a>
  <ul class="collapse">
  <li><a href="#overview-of-the-comparative-framework" id="toc-overview-of-the-comparative-framework" class="nav-link" data-scroll-target="#overview-of-the-comparative-framework">Overview of the comparative framework</a></li>
  <li><a href="#simulating-networks" id="toc-simulating-networks" class="nav-link" data-scroll-target="#simulating-networks">Simulating networks</a>
  <ul class="collapse">
  <li><a href="#table-s1.-summary-of-parameterisation-across-food-web-reconstruction-models" id="toc-table-s1.-summary-of-parameterisation-across-food-web-reconstruction-models" class="nav-link" data-scroll-target="#table-s1.-summary-of-parameterisation-across-food-web-reconstruction-models">Table S1. Summary of parameterisation across food web reconstruction models</a></li>
  </ul></li>
  <li><a href="#extinction-simulation-framework" id="toc-extinction-simulation-framework" class="nav-link" data-scroll-target="#extinction-simulation-framework">Extinction simulation framework</a></li>
  <li><a href="#effect-of-body-size-sampling-method-on-network-metrics" id="toc-effect-of-body-size-sampling-method-on-network-metrics" class="nav-link" data-scroll-target="#effect-of-body-size-sampling-method-on-network-metrics">Effect of Body Size Sampling Method on Network Metrics</a>
  <ul class="collapse">
  <li><a href="#figure-s1.-effect-of-body-size-sampling-method-on-network-metrics" id="toc-figure-s1.-effect-of-body-size-sampling-method-on-network-metrics" class="nav-link" data-scroll-target="#figure-s1.-effect-of-body-size-sampling-method-on-network-metrics">Figure S1. Effect of Body Size Sampling Method on Network Metrics</a></li>
  </ul></li>
  <li><a href="#parameterisation-of-the-body-mass-ratio-model" id="toc-parameterisation-of-the-body-mass-ratio-model" class="nav-link" data-scroll-target="#parameterisation-of-the-body-mass-ratio-model">Parameterisation of the body-mass ratio model</a>
  <ul class="collapse">
  <li><a href="#table-s2.-parameter-perturbation-classes-for-the-bmr-model" id="toc-table-s2.-parameter-perturbation-classes-for-the-bmr-model" class="nav-link" data-scroll-target="#table-s2.-parameter-perturbation-classes-for-the-bmr-model">Table S2. Parameter perturbation classes for the BMR model</a></li>
  <li><a href="#effects-of-body-mass-interaction-parameterisation-on-network-structure" id="toc-effects-of-body-mass-interaction-parameterisation-on-network-structure" class="nav-link" data-scroll-target="#effects-of-body-mass-interaction-parameterisation-on-network-structure">Effects of body-mass interaction parameterisation on network structure</a></li>
  </ul></li>
  <li><a href="#downsampling-pfim-networks" id="toc-downsampling-pfim-networks" class="nav-link" data-scroll-target="#downsampling-pfim-networks">Downsampling PFIM networks</a></li>
  </ul></li>
  <li><a href="#analyses" id="toc-analyses" class="nav-link" data-scroll-target="#analyses">Analyses</a>
  <ul class="collapse">
  <li><a href="#multivariate-analysis-of-network-structure" id="toc-multivariate-analysis-of-network-structure" class="nav-link" data-scroll-target="#multivariate-analysis-of-network-structure">Multivariate analysis of network structure</a></li>
  <li><a href="#beta-diversity-of-network-structure" id="toc-beta-diversity-of-network-structure" class="nav-link" data-scroll-target="#beta-diversity-of-network-structure"><span class="math inline">\(\beta\)</span>-diversity of network structure</a></li>
  <li><a href="#quantification-of-extinction-simulation-outcomes-and-model-concordance" id="toc-quantification-of-extinction-simulation-outcomes-and-model-concordance" class="nav-link" data-scroll-target="#quantification-of-extinction-simulation-outcomes-and-model-concordance">Quantification of extinction simulation outcomes and model concordance</a></li>
  <li><a href="#anova-and-temporal-dynamics-analysis" id="toc-anova-and-temporal-dynamics-analysis" class="nav-link" data-scroll-target="#anova-and-temporal-dynamics-analysis">ANOVA and temporal dynamics analysis</a></li>
  </ul></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
</div>
<main class="content quarto-banner-title-block" id="quarto-document-content">      

       <section id="model-descriptions" class="level1">
<h1>Model descriptions</h1>
<section id="structural-models" class="level2">
<h2 class="anchored" data-anchor-id="structural-models">Structural models</h2>
<section id="random-model" class="level3">
<h3 class="anchored" data-anchor-id="random-model">Random model</h3>
<p>The Erdős–Rényi random graph model <span class="citation" data-cites="erdos1959">(<a href="#ref-erdos1959" role="doc-biblioref">Erdős and Rényi 1959</a>)</span> assigns a fixed number of links (<span class="math inline">\(L\)</span>) uniformly at random among a set of <span class="math inline">\(S\)</span> nodes (species). Ecologically, this model assumes that interactions occur independently of species identity, such that no node-level traits influence whether a link is present or absent. As a result, links are randomly distributed throughout the network, producing a food web that is minimally biologically structured while preserving the specified richness (<span class="math inline">\(S\)</span>) and connectance (<span class="math inline">\(L/S^{2}\)</span>). Because connectance is defined as <span class="math inline">\(Co = L/S^{2}\)</span>, specifying either <span class="math inline">\(L\)</span> or <span class="math inline">\(Co\)</span> fully determines network density. Here we parameterise the model using <span class="math inline">\(L\)</span> as derived from the drawn Co value <em>i.e.,</em> <span class="math inline">\(L = Co \times S^{2}\)</span>.</p>
</section>
<section id="niche-model" class="level3">
<h3 class="anchored" data-anchor-id="niche-model">Niche model</h3>
<p>The niche model <span class="citation" data-cites="williams2000">(<a href="#ref-williams2000" role="doc-biblioref">Williams and Martinez 2000</a>)</span> assumes that trophic interactions are structured by a one-dimensional feeding niche. Each species is assigned a niche range, and all species whose niche values fall within this range are potential prey, allowing for cannibalism. Niche ranges are assigned stochastically, with their sizes constrained in part by the specified connectance (<span class="math inline">\(Co\)</span>) of the network. Although several extensions of the niche model have been proposed, increasing model complexity does not appear to improve its ability to reproduce empirically realistic network structure <span class="citation" data-cites="williams2008">(<a href="#ref-williams2008" role="doc-biblioref">Williams and Martinez 2008</a>)</span>.</p>
<p>Formally, each of the <span class="math inline">\(S\)</span> species is assigned a niche value <span class="math inline">\(n_i\)</span> drawn uniformly from the interval [0,1]. Species <span class="math inline">\(i\)</span> consumes all species whose niche values fall within a contiguous range of width <span class="math inline">\(r_i\)</span>, with the center of this range (<span class="math inline">\(c_i\)</span>) drawn uniformly from the interval <span class="math inline">\([ \frac{r_i}{2}, n_i ]\)</span>. The range width <span class="math inline">\(r_i\)</span> is determined by drawing a value from a beta distribution on [0,1] with expected value <span class="math inline">\(2 \times Co\)</span>, which is then multiplied by <span class="math inline">\(n_i\)</span> to achieve the desired connectance.</p>
</section>
</section>
<section id="realised-models" class="level2">
<h2 class="anchored" data-anchor-id="realised-models">Realised models</h2>
<section id="allometric-diet-breadth-model" class="level3">
<h3 class="anchored" data-anchor-id="allometric-diet-breadth-model">Allometric diet breadth model</h3>
<p>The Allometric Diet Breadth Model (ADBM; <span class="citation" data-cites="petchey2008">Petchey et al. (<a href="#ref-petchey2008" role="doc-biblioref">2008</a>)</span>) is grounded in optimal foraging theory and predicts trophic interactions based on energetic considerations. In this framework, consumers select prey to maximize their rate of energy intake, such that diet composition is determined by the energetic profitability of potential resources. The model therefore predicts both the number of trophic links and their arrangement based on species-level traits, specifically consumer diet breadth.</p>
<p>The energy intake rate (<span class="math inline">\(K\)</span>) of a consumer is defined as:</p>
<p><span class="math display">\[
K = \frac{\sum_{i=1}^{k}\lambda_{ij}E_{i}}{1+\sum_{i=1}^{k}\lambda_{ij}H_{ij}}
\]</span></p>
<p>where <span class="math inline">\(\lambda_{ij}\)</span> is the encounter rate between consumer <span class="math inline">\(j\)</span> and resource <span class="math inline">\(i\)</span>, defined as the product of attack rate (<span class="math inline">\(A_i\)</span>) and resource density (<span class="math inline">\(N_i\)</span>), <span class="math inline">\(E_i\)</span> is the energy content of the resource, and <span class="math inline">\(H_{ij}\)</span> is the handling time. Handling time depends on the ratio of consumer to resource body mass and is defined as:</p>
<p><span class="math display">\[
H_{ij} = \frac{h}{b - \frac{M_{i}}{M_{j}}} if \frac{M_{i}}{M_{j}} &lt; b
\]</span></p>
<p>and</p>
<p><span class="math display">\[
H_{ij} = \infty \geq b
\]</span></p>
<p>All bioenergetic and allometric parameters were fixed to the default values reported in <span class="citation" data-cites="petchey2008">Petchey et al. (<a href="#ref-petchey2008" role="doc-biblioref">2008</a>)</span> and were not estimated from data. Attack rates, handling times, and resource densities were parameterised as power-law functions of body mass using empirically derived scaling exponents, while energy content was assumed to scale linearly with prey body mass. Body mass was therefore the sole varying biological input to the model across replicates, with all other parameters held constant.</p>
</section>
<section id="allometric-trophic-network-model" class="level3">
<h3 class="anchored" data-anchor-id="allometric-trophic-network-model">Allometric trophic network model</h3>
<p>The Allometric Trophic Network (ATN; <span class="citation" data-cites="brose2006">Brose et al. (<a href="#ref-brose2006" role="doc-biblioref">2006</a>)</span>) model also uses body mass to infer trophic interactions but places greater emphasis on mechanical constraints associated with consumer–resource size relationships. Interactions are determined by allometric rules based on the ratio of consumer (<span class="math inline">\(M_i\)</span>) to resource (<span class="math inline">\(M_j\)</span>) body mass and are further constrained to produce networks that resemble realized food webs <span class="citation" data-cites="schneider2016 gauzens2023">(<a href="#ref-schneider2016" role="doc-biblioref">Schneider et al. 2016</a>; <a href="#ref-gauzens2023" role="doc-biblioref">Gauzens et al. 2023</a>)</span>.</p>
<p>The probability of a trophic interaction (<span class="math inline">\(P_{ij}\)</span>) between consumer <span class="math inline">\(i\)</span> and resource <span class="math inline">\(j\)</span> is defined using a Ricker function parameterized by the optimal body-mass ratio (<span class="math inline">\(R_{opt}\)</span>) and the shape parameter <span class="math inline">\(\gamma\)</span>:</p>
<p><span class="math display">\[
P_{ij} = (L \times \exp(1 - L))^{\gamma}
\]</span></p>
<p>where</p>
<p><span class="math display">\[
L = \frac{M_{i}}{M_{j} \times R_{opt}}
\]</span></p>
<p>An optional threshold can be applied to <span class="math inline">\(P_{ij}\)</span>, such that interaction probabilities below the threshold are set to zero, further constraining network structure.</p>
<p>All bioenergetic and allometric parameters were fixed to the default values reported in <span class="citation" data-cites="petchey2008">Petchey et al. (<a href="#ref-petchey2008" role="doc-biblioref">2008</a>)</span>, which were originally evaluated across a range of empirical food webs spanning both terrestrial and aquatic systems. Although these parameterisations are not derived specifically from paleo communities, previous work has shown that ADBM structural predictions are relatively robust to variation in scaling exponents across ecosystem types. As our analyses focus on comparative differences among reconstruction approaches rather than absolute parameter calibration, using a consistent, empirically grounded parameter set provides a standardised baseline for comparison.</p>
</section>
<section id="body-size-ratio-model" class="level3">
<h3 class="anchored" data-anchor-id="body-size-ratio-model">Body size ratio model</h3>
<p>The body size ratio model <span class="citation" data-cites="rohr2010">(<a href="#ref-rohr2010" role="doc-biblioref">Rohr et al. 2010</a>)</span> infers trophic interactions probabilistically based on the ratio of consumer (<span class="math inline">\(M_i\)</span>) to resource (<span class="math inline">\(M_j\)</span>) body mass. To represent predator–prey body-mass ratios as a feeding niche, the model modifies this ratio using a quadratic function in log-transformed mass space, producing a unimodal interaction probability distribution. In its simplified form, the probability of an interaction between consumer <span class="math inline">\(i\)</span> and resource <span class="math inline">\(j\)</span> is defined as:</p>
<p><span class="math display">\[
P_{ij} = \frac{p}{1+p}
\]</span></p>
<p>where</p>
<p><span class="math display">\[
p = exp[\alpha + \beta log(\frac{M_{i}}{M_{j}}) + \gamma log^{2}(\frac{M_{i}}{M_{j}})]
\]</span></p>
<p>The original latent-trait formulation introduced by <span class="citation" data-cites="rohr2010">Rohr et al. (<a href="#ref-rohr2010" role="doc-biblioref">2010</a>)</span> included an additional interaction term, <span class="math inline">\(v_i \delta f_j\)</span>. For simplicity, and following <span class="citation" data-cites="yeakel2014">Yeakel et al. (<a href="#ref-yeakel2014" role="doc-biblioref">2014</a>)</span>, this term is omitted here and only the equation above is used. Parameter values are taken directly from <span class="citation" data-cites="yeakel2014">Yeakel et al. (<a href="#ref-yeakel2014" role="doc-biblioref">2014</a>)</span>, which were estimated using Serengeti food web data: <span class="math inline">\(\alpha = 1.41\)</span>, <span class="math inline">\(\beta = 3.75\)</span>, and <span class="math inline">\(\gamma = 1.87\)</span>.</p>
<p>Although the body size ratio model is parameterised using empirical estimates derived from terrestrial systems (<em>e.g.,</em> Serengeti food webs), its applicability to paleo communities may be less direct. To address this, we explicitly evaluated the sensitivity of network structure (see <em>Parameterisation of the body-mass ratio model</em> section) to variation in key parameters governing interaction probabilities.</p>
</section>
</section>
<section id="feasibility-models" class="level2">
<h2 class="anchored" data-anchor-id="feasibility-models">Feasibility models</h2>
<section id="paleo-food-web-inference-model" class="level3">
<h3 class="anchored" data-anchor-id="paleo-food-web-inference-model">Paleo food web inference model</h3>
<p>The Paleo Food Web Inference Model (PFIM; <span class="citation" data-cites="shaw2024">Shaw et al. (<a href="#ref-shaw2024" role="doc-biblioref">2024</a>)</span>) infers trophic interactions using a rule-based framework applied to discrete trait categories, such as habitat preference and body size. For a given consumer–resource pair, an interaction is deemed feasible only if all trait-based rules across multiple rule classes are satisfied.</p>
<p>The original implementation of PFIM includes an optional downsampling step adapted from <span class="citation" data-cites="roopnarine2006">Roopnarine (<a href="#ref-roopnarine2006" role="doc-biblioref">2006</a>)</span>, which prunes interactions using a power-law distribution defined by the expected link distribution. This approach is conceptually aligned with earlier feasibility-based methods <span class="citation" data-cites="roopnarine2006">(<a href="#ref-roopnarine2006" role="doc-biblioref">Roopnarine 2006</a>)</span> but does not require explicit assignment of taxa to trophic guilds. We follow the implementation described by <span class="citation" data-cites="shaw2024">Shaw et al. (<a href="#ref-shaw2024" role="doc-biblioref">2024</a>)</span>, as these approaches are based on the same underlying feasibility framework and are expected to generate highly similar network structures.</p>
</section>
</section>
</section>
<section id="network-construction" class="level1">
<h1>Network construction</h1>
<section id="overview-of-the-comparative-framework" class="level2">
<h2 class="anchored" data-anchor-id="overview-of-the-comparative-framework">Overview of the comparative framework</h2>
<p>All food-web reconstruction approaches were evaluated within a unified comparative framework in which each model generated ensembles of binary interaction networks under identical species richness and sampling structure. This design allows direct comparison of emergent network properties while controlling for variation in species identity, temporal sampling, and stochastic realisations. Each reconstructed food web is represented as a directed binary adjacency matrix <span class="math inline">\(A_{ij}\)</span>, where <span class="math inline">\(A_{ij} = 1\)</span> denotes a trophic interaction from consumer <span class="math inline">\(i\)</span> to resource <span class="math inline">\(j\)</span>, and <span class="math inline">\(A_{ij} = 0\)</span> otherwise. Unless otherwise stated, all analyses are based on binary interaction structure.</p>
<p>Reconstruction approaches differ primarily in their generative assumptions: (i) random models assume interactions occur independently of species identity, (ii) niche- and body-size–based models impose trait-structured constraints in latent or observed trait space, (iii) allometric models incorporate mechanistic energetic or size-ratio constraints on interaction feasibility, and (iv) feasibility-based models (PFIM) impose deterministic rule sets derived from discrete ecological traits.</p>
<p>For each model and time period, multiple stochastic realisations were generated to capture intrinsic variability. Reported results therefore reflect ensemble-level properties rather than single deterministic networks.</p>
</section>
<section id="simulating-networks" class="level2">
<h2 class="anchored" data-anchor-id="simulating-networks">Simulating networks</h2>
<p>Food webs were generated for each reconstruction approach using a consistent simulation framework designed to ensure comparability across models. For each model and time period, multiple independent network realisations were constructed (replicates), allowing stochastic variation in link structure to be quantified and propagated through subsequent analyses. All networks were built with identical species richness and based on a shared species pool, ensuring that differences in network structure arise solely from model-specific assumptions about interaction formation.</p>
<p>For models requiring continuous traits (<em>e.g.,</em> ADBM, ATN, and body size ratio models), species body masses were assigned probabilistically for each replicate. Body mass values were drawn from a predefined distribution (log-scaled), and these values served as the primary input governing interaction probabilities or energetic constraints. As a result, each replicate represents a unique realisation of trait space, generating variation in network topology even under identical model parameterisation.</p>
<p>In contrast, feasibility-based approaches (<em>e.g.,</em> PFIM) used discrete trait assignments (e.g., trophic guild, motility, tiering), which were fixed for a given time period. Stochasticity in these models arises primarily through optional link pruning or sampling procedures rather than variation in trait values.</p>
<p>For each model–time combination, an ensemble of network replicates (n ≈ 50 per configuration) was generated. These ensembles form the basis for all downstream analyses, including structural comparisons, beta diversity calculations, and extinction simulations. By maintaining consistent replication across models, the framework captures both deterministic differences among reconstruction approaches and their inherent stochastic variability.</p>
<section id="table-s1.-summary-of-parameterisation-across-food-web-reconstruction-models" class="level3">
<h3 class="anchored" data-anchor-id="table-s1.-summary-of-parameterisation-across-food-web-reconstruction-models">Table S1. Summary of parameterisation across food web reconstruction models</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 18%">
<col style="width: 18%">
<col style="width: 24%">
<col style="width: 18%">
<col style="width: 18%">
</colgroup>
<thead>
<tr class="header">
<th>Model</th>
<th>Parameter</th>
<th>Value / Distribution</th>
<th>Source / Implementation</th>
<th>Notes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Random</strong></td>
<td>Species richness (S)</td>
<td>Empirical (per community)</td>
<td>Input data</td>
<td>Shared across all models</td>
</tr>
<tr class="even">
<td></td>
<td>Number of links (L)</td>
<td>($L = Co S^2$), with ($Co U(0.07, 0.15)$)</td>
<td>This study</td>
<td>Connectance randomly drawn per replicate</td>
</tr>
<tr class="odd">
<td><strong>Niche</strong></td>
<td>Species richness (S)</td>
<td>Empirical</td>
<td>Input data</td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>Connectance (Co)</td>
<td>($Co U(0.07, 0.15)$)</td>
<td>This study</td>
<td>Determines niche range distribution</td>
</tr>
<tr class="odd">
<td></td>
<td>Niche values ($n_i$)</td>
<td>($U(0,1)$)</td>
<td>Standard niche model</td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>Range distribution</td>
<td>Beta distribution with mean</td>
<td>Standard niche model</td>
<td>As in <span class="citation" data-cites="williams2000">Williams and Martinez (<a href="#ref-williams2000" role="doc-biblioref">2000</a>)</span></td>
</tr>
<tr class="odd">
<td><strong>ADBM</strong></td>
<td>Body mass ($M_i$)</td>
<td>Uniform within size classes (see below)</td>
<td>This study</td>
<td>Primary varying trait</td>
</tr>
<tr class="even">
<td></td>
<td>Biomass ($B_i$)</td>
<td>($M_i^{-3/4}$)</td>
<td>Metabolic scaling</td>
<td>Used in encounter rates</td>
</tr>
<tr class="odd">
<td></td>
<td>Attack rate, handling time, energy scaling</td>
<td>Fixed allometric exponents</td>
<td><span class="citation" data-cites="petchey2008">Petchey et al. (<a href="#ref-petchey2008" role="doc-biblioref">2008</a>)</span></td>
<td>Default parameter set</td>
</tr>
<tr class="even">
<td></td>
<td>Resource density ($N_i$)</td>
<td>Derived from biomass</td>
<td>This study</td>
<td>Implicit in encounter term</td>
</tr>
<tr class="odd">
<td><strong>ATN / L-matrix</strong></td>
<td>Body mass ($M_i$)</td>
<td>Uniform within size classes</td>
<td>This study</td>
<td>Same as ADBM</td>
</tr>
<tr class="even">
<td></td>
<td>Producer identity</td>
<td>Binary (from tiering)</td>
<td>Empirical data</td>
<td>Constrains trophic structure</td>
</tr>
<tr class="odd">
<td></td>
<td>Interaction rules</td>
<td>Deterministic size-structured constraints</td>
<td>Schneider et al.&nbsp;(2016) implementation</td>
<td>I</td>
</tr>
<tr class="even">
<td><strong>Body-mass ratio (BMR)</strong></td>
<td>Body mass ($M_i$)</td>
<td>Uniform within size classes</td>
<td>This study</td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td>α (optimum ratio)</td>
<td>1.41</td>
<td><span class="citation" data-cites="yeakel2014">Yeakel et al. (<a href="#ref-yeakel2014" role="doc-biblioref">2014</a>)</span></td>
<td>Serengeti-derived</td>
</tr>
<tr class="even">
<td></td>
<td>β (niche width)</td>
<td>3.73</td>
<td><span class="citation" data-cites="yeakel2014">Yeakel et al. (<a href="#ref-yeakel2014" role="doc-biblioref">2014</a>)</span></td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td>γ (scaling / threshold)</td>
<td>−1.90</td>
<td><span class="citation" data-cites="yeakel2014">Yeakel et al. (<a href="#ref-yeakel2014" role="doc-biblioref">2014</a>)</span></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>Functional form</td>
<td>Quadratic in log mass ratio</td>
<td><span class="citation" data-cites="rohr2010">Rohr et al. (<a href="#ref-rohr2010" role="doc-biblioref">2010</a>)</span></td>
<td>Simplified formulation</td>
</tr>
<tr class="odd">
<td><strong>PFIM (downsampled)</strong></td>
<td>Trait rules</td>
<td>Feeding, motility, tiering</td>
<td><span class="citation" data-cites="shaw2024">Shaw et al. (<a href="#ref-shaw2024" role="doc-biblioref">2024</a>)</span></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>Downsampling parameter (y)</td>
<td>100.0</td>
<td>This study</td>
<td>Power-law pruning</td>
</tr>
<tr class="odd">
<td><strong>All models</strong></td>
<td>Body size classes</td>
<td>Discrete categories (tiny → gigantic)</td>
<td>Empirical data</td>
<td>Mapped to continuous mass</td>
</tr>
<tr class="even">
<td></td>
<td>Body mass sampling</td>
<td>Uniform within class ranges</td>
<td>This study</td>
<td>Re-sampled per replicate</td>
</tr>
<tr class="odd">
<td></td>
<td>Replicates</td>
<td>(n = 100)</td>
<td>This study</td>
<td>Captures stochastic variation</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="extinction-simulation-framework" class="level2">
<h2 class="anchored" data-anchor-id="extinction-simulation-framework">Extinction simulation framework</h2>
<p>To evaluate structural robustness, reconstructed networks were subjected to simulated species removal sequences representing alternative disturbance regimes. These included random extinction, degree-ordered extinction (based on generality and vulnerability), and trait-ordered extinction sequences derived from ecological hierarchies as defined in <span class="citation" data-cites="dunhill2024">Dunhill et al. (<a href="#ref-dunhill2024" role="doc-biblioref">2024</a>)</span>.</p>
<p>Following each removal event, secondary extinctions were computed dynamically as species losing all incoming trophic resources. This process generates cascading extinction dynamics dependent on underlying network topology.</p>
<p>All extinction regimes were applied consistently across reconstruction models and network realisations to ensure comparability of cascading structural responses.</p>
</section>
<section id="effect-of-body-size-sampling-method-on-network-metrics" class="level2">
<h2 class="anchored" data-anchor-id="effect-of-body-size-sampling-method-on-network-metrics">Effect of Body Size Sampling Method on Network Metrics</h2>
<p>To assess whether the choice of body size sampling distribution (uniform, lognormal, or truncated lognormal) influences the estimated structure of ecological networks, we computed partial eta-squared (η²) values for each network metric within each reconstruction model. This approach isolates the effect of body size distribution while controlling for model-specific variation.</p>
<p>Across all models and network metrics, the effect of body size sampling method was extremely small. Most η² values were effectively zero (&lt;0.01), indicating that the choice of distribution had negligible influence on metrics such as connectance, generality, vulnerability, and various motif counts. Only a few metrics in the ATN and ADBM models showed slightly higher effects (η² ≈ 0.17 for max trophic level and the number of linear chains), but these remained the exception rather than the rule.</p>
<p>These findings justify using any of the tested body size sampling approaches for our simulations, as the structural conclusions drawn from the networks are robust to this methodological choice. Consequently, analyses of network metrics and comparisons across reconstruction models are not confounded by the specific form of the synthetic body size distribution.</p>
<section id="figure-s1.-effect-of-body-size-sampling-method-on-network-metrics" class="level3">
<h3 class="anchored" data-anchor-id="figure-s1.-effect-of-body-size-sampling-method-on-network-metrics">Figure S1. Effect of Body Size Sampling Method on Network Metrics</h3>
<p><a href="figures/effect_size_bodysize_within_model.png" class="lightbox" data-gallery="quarto-lightbox-gallery-1"><img src="figures/effect_size_bodysize_within_model.png" class="img-fluid"></a></p>
<p>Metrics where η² was notably higher are labelled directly on the bars. The figure highlights that, for the majority of network properties and models, η² values are extremely low (&lt;0.01), confirming that the body size distribution choice has negligible impact on network structure. A few exceptions appear for the ATN model, but these are limited to specific metrics (<em>e.g.,</em> number of linear chains).</p>
</section>
</section>
<section id="parameterisation-of-the-body-mass-ratio-model" class="level2">
<h2 class="anchored" data-anchor-id="parameterisation-of-the-body-mass-ratio-model">Parameterisation of the body-mass ratio model</h2>
<p>To evaluate the sensitivity of the body-mass ratio (BMR) reconstruction model to assumptions about feeding niche structure and interaction filtering, we defined a set of seven parameter configurations spanning biologically plausible perturbations of the interaction probability function.</p>
<p>The BMR model defines trophic link probability as a function of predator–prey body-mass ratios and interaction structure is governed by three parameters controlling niche position, niche width, and interaction thresholding.</p>
<p>We explored seven parameter sets (Table Sx), constructed to isolate distinct mechanistic perturbations of this function.</p>
<section id="table-s2.-parameter-perturbation-classes-for-the-bmr-model" class="level3">
<h3 class="anchored" data-anchor-id="table-s2.-parameter-perturbation-classes-for-the-bmr-model">Table S2. Parameter perturbation classes for the BMR model</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 18%">
<col style="width: 18%">
<col style="width: 18%">
<col style="width: 18%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Parameter set</th>
<th>α (optimum ratio)</th>
<th>β (niche width)</th>
<th>γ (threshold / scaling)</th>
<th>Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>baseline</td>
<td>1.41</td>
<td>3.73</td>
<td>-1.90</td>
<td>Serengeti-calibrated reference model</td>
</tr>
<tr class="even">
<td>narrow_niche</td>
<td>1.41</td>
<td>2.5</td>
<td>-1.90</td>
<td>Increased dietary specialization</td>
</tr>
<tr class="odd">
<td>wide_niche</td>
<td>1.41</td>
<td>5.0</td>
<td>-1.90</td>
<td>Relaxed dietary specialization</td>
</tr>
<tr class="even">
<td>shifted_optimum_low</td>
<td>1.0</td>
<td>3.73</td>
<td>-1.90</td>
<td>Smaller optimal predator–prey ratio</td>
</tr>
<tr class="odd">
<td>shifted_optimum_high</td>
<td>1.8</td>
<td>3.73</td>
<td>-1.90</td>
<td>Larger optimal predator–prey ratio</td>
</tr>
<tr class="even">
<td>strict_threshold</td>
<td>1.41</td>
<td>3.73</td>
<td>-2.5</td>
<td>Stronger interaction filtering</td>
</tr>
<tr class="odd">
<td>relaxed_threshold</td>
<td>1.41</td>
<td>3.73</td>
<td>-1.0</td>
<td>Weaker interaction filtering</td>
</tr>
</tbody>
</table>
<p>These parameterisations represent structured deviations from the empirically calibrated baseline, allowing us to separate effects of niche breadth, interaction optima, and interaction filtering strength.</p>
</section>
<section id="effects-of-body-mass-interaction-parameterisation-on-network-structure" class="level3">
<h3 class="anchored" data-anchor-id="effects-of-body-mass-interaction-parameterisation-on-network-structure">Effects of body-mass interaction parameterisation on network structure</h3>
<p>Multivariate analysis revealed that parameterisation of the body-mass ratio interaction model significantly influenced emergent food-web structure (PERMANOVA, R² = 0.227, F = 136.38, p = 0.001). Although statistically highly significant, this effect explains approximately one-fifth of total variation in multivariate network structure, indicating that parameter choice systematically shapes but does not dominate network topology.</p>
<p>Redundancy analysis (RDA) confirmed that this variation is primarily low-dimensional. The first canonical axis captured the majority of explainable variation among parameter sets (RDA1 F = 781.06, p = 0.001), with a secondary axis also contributing meaningfully (RDA2 F = 32.52, p = 0.001), while subsequent axes were comparatively minor (RDA3 F = 4.46, p = 0.031; RDA4 non-significant). This indicates that differences among parameterisations are structured along a small number of dominant gradients rather than reflecting fully distinct multivariate regimes.</p>
<p>Inspection of RDA loadings indicates that this structure is primarily driven by variation in connectance and measures of trophic organisation (notably generality and vulnerability), whereas richness and trophic level contribute comparatively weakly. Thus, parameter variation primarily reshapes interaction density and the distribution of consumer–resource breadth, rather than fundamentally altering overall network organisation.</p>
<p>Despite significant differences in multivariate centroids, there was no evidence that parameter sets differ in multivariate dispersion (betadisper, F = 0.154, p = 0.988). This indicates that while parameter choice shifts the mean position of networks in multivariate space, it does not systematically alter the variability of structures generated within each parameter regime.</p>
<p>###&nbsp;Justification for baseline parameterisation</p>
<p>Given that parameter variation induces structured but low-dimensional shifts in network topology, we retain the baseline parameter set (α = 1.41, β = 3.73, γ = −1.90; derived from empirical Serengeti estimates) for subsequent analyses.</p>
<p>This choice is justified for three reasons:</p>
<ul>
<li><p><strong>Empirical grounding:</strong> The baseline parameters are derived from well-resolved empirical food webs and therefore represent biologically realistic interaction constraints rather than arbitrary tuning.</p></li>
<li><p><strong>Structural robustness:</strong> Although alternative parameterisations modify network properties, these changes occur primarily along a single dominant structural axis rather than producing qualitatively distinct network regimes. Thus, conclusions are robust to reasonable variation in parameter choice.</p></li>
<li><p><strong>Avoiding overfitting of generative assumptions:</strong> Exploring extreme parameter regimes (<em>e.g.,</em> narrow niche, relaxed thresholds) expands structural variance but does not improve biological realism. Using empirically informed baseline parameters prevents artificially inflating or distorting ecological inference.</p></li>
</ul>
<p>Overall, body size interaction parameters influence emergent food web structure in a systematic but constrained manner. Rather than defining fundamentally different network architectures, parameter variation reshapes networks along a single dominant gradient of interaction density and trophic role breadth. This analysis demonstrates that, although parameter choice influences interaction density and trophic breadth, the resulting variation is constrained and does not produce qualitatively different network structures, supporting the applicability of the model to systems that differ from the original calibration context.</p>
</section>
</section>
<section id="downsampling-pfim-networks" class="level2">
<h2 class="anchored" data-anchor-id="downsampling-pfim-networks">Downsampling PFIM networks</h2>
<p>To assess the optimal downsampling parameter to use so as to allow some variation in network structure we downsampled PFIM metawebs across the following range: 5.0, 10.0, 20.0, 30.0, 50.0, 100.0. We then calculated the Jaccard similarity of the resulting adjacency matrices. Across the parameter range the similarity of networks tended to remain above 0.6 and a downsampling parameter of 100 had a mean similarity of 0.86. We thus used a downsampling parameter of 100 for all of the PFIM networks for all statistical analyses.</p>
</section>
</section>
<section id="analyses" class="level1">
<h1>Analyses</h1>
<section id="multivariate-analysis-of-network-structure" class="level2">
<h2 class="anchored" data-anchor-id="multivariate-analysis-of-network-structure">Multivariate analysis of network structure</h2>
<p>We quantified food-web structure using a suite of macro-, meso-, and micro-scale network metrics capturing global topology, motif composition, and species-level interaction patterns (Table S1). Differences among reconstruction approaches were assessed using a multivariate analysis of variance (MANOVA), with model identity as a fixed factor and the full set of network metrics as response variables. Pillai’s trace was used to assess overall multivariate significance due to its robustness to violations of multivariate normality. To identify the multivariate axes driving differences among models, we performed canonical discriminant analysis (CDA) on the MANOVA model. Canonical variates represent orthogonal linear combinations of network metrics that maximise separation among reconstruction approaches. The contribution of individual metrics to each canonical variate was quantified using canonical structure coefficients (correlations between original metrics and canonical scores).</p>
<p>For visualisation, canonical scores were plotted using linear discriminant analysis (LDA), which yields an equivalent discriminant subspace under equal group priors. Model separation in canonical space was visualised using convex hulls encompassing all network replicates for each reconstruction approach. Univariate analyses of variance and effect sizes (partial η²) were calculated for individual metrics and are reported in the Supplementary Materials for descriptive comparison. Pairwise interaction turnover was quantified using link-based beta diversity, which measures dissimilarity in the identity of trophic interactions between networks and captures differences arising from species turnover or changes in interactions among shared species.</p>
</section>
<section id="beta-diversity-of-network-structure" class="level2">
<h2 class="anchored" data-anchor-id="beta-diversity-of-network-structure"><span class="math inline">\(\beta\)</span>-diversity of network structure</h2>
<p>Structural dissimilarity between networks was quantified using interaction-based beta diversity, decomposed into complementary components:</p>
<ul>
<li><p>βS: total interaction dissimilarity</p></li>
<li><p>βWN: interaction rewiring among shared species</p></li>
<li><p>βOS: species turnover–driven interaction change</p></li>
</ul>
<p>These metrics partition differences between networks into contributions arising from species loss versus rewiring of interactions among shared species.</p>
<p>Together, they define a multilevel decomposition of structural divergence in food-web topology across models and time periods.</p>
</section>
<section id="quantification-of-extinction-simulation-outcomes-and-model-concordance" class="level2">
<h2 class="anchored" data-anchor-id="quantification-of-extinction-simulation-outcomes-and-model-concordance">Quantification of extinction simulation outcomes and model concordance</h2>
<p>To evaluate how reconstruction framework influenced inferred extinction dynamics, simulated community states were compared against observed or expected reference states using two complementary approaches. First, deviation in continuous network metrics (e.g., connectance, mean trophic level, modularity) was quantified using mean absolute difference (MAD). For each metric and time step, MAD was calculated as:</p>
<p><span class="math inline">\(MAD = \frac{1}{n} \sum_{i=1}^{n} | M_{i}^{sim} - M_{i}^{ref}|\)</span></p>
<p>where <span class="math inline">\(M_{i}^{sim}\)</span> is the simulated value and <span class="math inline">\(M_{i}^{ref}\)</span> is the corresponding observed or expected value. MAD was chosen because it provides a scale-preserving measure of deviation that is less sensitive to extreme values than squared-error metrics and allows direct comparison across reconstruction frameworks.</p>
<p>Second, agreement in predicted persistence outcomes was evaluated using a modified True Skill Statistic (TSS) at both node and link levels. At the node level, species were classified as present (persisting) or absent (extinct) in each simulated network and compared to their presence–absence status in the reference community.</p>
<p>At the link level, each possible species pair was classified according to the presence or absence of a trophic interaction in the simulated versus reference network. Thus, link-level evaluation quantified agreement in the retention or loss of specific trophic interactions, independent of overall species richness.</p>
<p>For both node- and link-level classifications, outcomes were assigned as true positives (TP), true negatives (TN), false positives (FP), or false negatives (FN), and TSS was calculated as:</p>
<p>TSS = Sensitivity + Specificity − 1</p>
<p>where Sensitivity = TP/(TP + FN) and Specificity = TN/(TN + FP). TSS ranges from −1 to 1, with 1 indicating perfect agreement, 0 indicating performance no better than random expectation, and negative values indicating systematic disagreement. Because TSS is prevalence-independent, it is appropriate for extinction simulations in which class imbalance may occur (<em>e.g.,</em> many persisting species or many absent links).</p>
</section>
<section id="anova-and-temporal-dynamics-analysis" class="level2">
<h2 class="anchored" data-anchor-id="anova-and-temporal-dynamics-analysis">ANOVA and temporal dynamics analysis</h2>
<p>This script quantifies how food web structure varies across reconstruction models and through time using a combination of two-way ANOVA, effect size estimation, and post hoc comparisons.</p>
<p>First, simulated network outputs are imported and standardised across models and time steps. A suite of network metrics spanning macro- (<em>e.g.,</em> connectance, trophic level), meso- (motif structure), and micro-scale (generality, vulnerability) properties are extracted and summarised. Descriptive statistics (mean ± SD) are calculated for each model–metric combination and exported for supplementary reporting.</p>
<p>To test for differences in network structure, separate two-way ANOVAs are fitted for each metric with reconstruction model and time (four stages: pre-, during, early, and late extinction) as fixed factors. Model assumptions are evaluated using Levene’s tests for homogeneity of variance and visual diagnostics (residual–fitted plots and Q–Q plots).</p>
<p>For each ANOVA, partial eta-squared values are calculated to quantify the relative importance of model choice, time, and their interaction. These effect sizes are used to compare how strongly each factor influences different aspects of network structure.</p>
<p>Temporal trajectories are then visualised by plotting mean metric values (± standard error) across time for each model, as well as relative changes from pre-extinction baselines. This allows direct comparison of how models differ in their predicted structural responses to extinction and recovery.</p>
<p>To assess agreement among models, the coefficient of variation (CV) is calculated across models for each metric and time step, providing a measure of inter-model disagreement through time.</p>
<p>Post hoc pairwise comparisons (Tukey-adjusted) are performed to identify which models differ significantly within each time step. These results are summarised as heatmaps showing the magnitude and significance of pairwise differences.</p>
<p>Finally, ANOVA effect sizes and model disagreement (CV) are combined into a synthesis plot, highlighting which metrics are primarily driven by model choice versus temporal dynamics, and where models converge or diverge most strongly.</p>
</section>
</section>
<section id="references" class="level1 unnumbered">
<h1 class="unnumbered">References</h1>
<div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-brose2006" class="csl-entry" role="listitem">
Brose, Ulrich, Tomas Jonsson, Eric L. Berlow, et al. 2006. <span>“Consumer<span></span>resource Body-Size Relationships in Natural Food Webs.”</span> <em>Ecology</em> 87 (10): 2411–17. https://doi.org/<a href="https://doi.org/10.1890/0012-9658(2006)87[2411:CBRINF]2.0.CO;2">https://doi.org/10.1890/0012-9658(2006)87[2411:CBRINF]2.0.CO;2</a>.
</div>
<div id="ref-dunhill2024" class="csl-entry" role="listitem">
Dunhill, Alexander M., Karolina Zarzyczny, Jack O. Shaw, Jed W. Atkinson, Crispin T. S. Little, and Andrew P. Beckerman. 2024. <span>“Extinction Cascades, Community Collapse, and Recovery Across a Mesozoic Hyperthermal Event.”</span> <em>Nature Communications</em> 15 (1): 8599. <a href="https://doi.org/10.1038/s41467-024-53000-2">https://doi.org/10.1038/s41467-024-53000-2</a>.
</div>
<div id="ref-erdos1959" class="csl-entry" role="listitem">
Erdős, P., and A. Rényi. 1959. <span>“On Random Graphs. i.”</span> <em>Publicationes Mathematicae Debrecen</em> 6 (3-4): 290–97. <a href="https://doi.org/10.5486/pmd.1959.6.3-4.12">https://doi.org/10.5486/pmd.1959.6.3-4.12</a>.
</div>
<div id="ref-gauzens2023" class="csl-entry" role="listitem">
Gauzens, Benoit, Ulrich Brose, Eva Delmas, and Emilio Berti. 2023. <span>“ATNr: Allometric Trophic Network Models in r.”</span> <em>Methods in Ecology and Evolution</em> 14 (11): 2766–73. <a href="https://doi.org/10.1111/2041-210X.14212">https://doi.org/10.1111/2041-210X.14212</a>.
</div>
<div id="ref-petchey2008" class="csl-entry" role="listitem">
Petchey, Owen L., Andrew P. Beckerman, Jens O. Riede, and Philip H. Warren. 2008. <span>“Size, Foraging, and Food Web Structure.”</span> <em>Proceedings of the National Academy of Sciences</em> 105 (11): 4191–96. <a href="https://doi.org/10.1073/pnas.0710672105">https://doi.org/10.1073/pnas.0710672105</a>.
</div>
<div id="ref-rohr2010" class="csl-entry" role="listitem">
Rohr, Rudolf&nbsp;Philippe, Heike Scherer, Patrik Kehrli, Christian Mazza, and Louis-Félix Bersier. 2010. <span>“Modeling Food Webs: Exploring Unexplained Structure Using Latent Traits.”</span> <em>The American Naturalist</em> 176 (2): 170–77. <a href="https://doi.org/10.1086/653667">https://doi.org/10.1086/653667</a>.
</div>
<div id="ref-roopnarine2006" class="csl-entry" role="listitem">
Roopnarine, Peter D. 2006. <span>“Extinction Cascades and Catastrophe in Ancient Food Webs.”</span> <em>Paleobiology</em> 32 (1): 1–19. <a href="https://www.jstor.org/stable/4096814">https://www.jstor.org/stable/4096814</a>.
</div>
<div id="ref-schneider2016" class="csl-entry" role="listitem">
Schneider, Florian D., Ulrich Brose, Björn C. Rall, and Christian Guill. 2016. <span>“Animal Diversity and Ecosystem Functioning in Dynamic Food Webs.”</span> <em>Nature Communications</em> 7 (1): 12718. <a href="https://doi.org/10.1038/ncomms12718">https://doi.org/10.1038/ncomms12718</a>.
</div>
<div id="ref-shaw2024" class="csl-entry" role="listitem">
Shaw, Jack O., Alexander M. Dunhill, Andrew P. Beckerman, Jennifer A. Dunne, and Pincelli M. Hull. 2024. <em>A Framework for Reconstructing Ancient Food Webs Using Functional Trait Data</em>. bioRxiv. <a href="https://doi.org/10.1101/2024.01.30.578036">https://doi.org/10.1101/2024.01.30.578036</a>.
</div>
<div id="ref-williams2000" class="csl-entry" role="listitem">
Williams, Richard J., and Neo D. Martinez. 2000. <span>“Simple Rules Yield Complex Food Webs.”</span> <em>Nature</em> 404 (6774): 180–83. <a href="https://doi.org/10.1038/35004572">https://doi.org/10.1038/35004572</a>.
</div>
<div id="ref-williams2008" class="csl-entry" role="listitem">
Williams, Richard J., and Neo D. Martinez. 2008. <span>“Success and its limits among structural models of complex food webs.”</span> <em>The Journal of Animal Ecology</em> 77 (3): 512–19. <a href="https://doi.org/10.1111/j.1365-2656.2008.01362.x">https://doi.org/10.1111/j.1365-2656.2008.01362.x</a>.
</div>
<div id="ref-yeakel2014" class="csl-entry" role="listitem">
Yeakel, Justin D., Mathias M. Pires, Lars Rudolf, et al. 2014. <span>“Collapse of an Ecological Network in Ancient Egypt.”</span> <em>PNAS</em> 111 (40): 14472–77. <a href="https://doi.org/10.1073/pnas.1408471111">https://doi.org/10.1073/pnas.1408471111</a>.
</div>
</div>
</section>
     </main>
<!-- /main column -->  <script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>  </div> <!-- /content -->  <script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script> 
  
</body></html>