"""
nichemodel(species, connectance)

    Wrapper of the structuralmodel(NicheModel) from SpeciesInteractionNetworks.jl.
    This allows the assignment of 'real' species names from your dataset 
    to the abstract nodes generated by the niche model.
"""
function nichemodel(species::Any, connectance::Float64)

    # 1. Determine the size of the community
    S = length(species)
    
    # 2. Generate the Niche Web
    # This uses the Williams & Martinez (2000) algorithm:
    # - Each species is assigned a niche value 'n_i' ~ Uniform(0,1)
    # - Each species is assigned a feeding range 'r_i' and a center 'c_i'
    # - Species i eats species j if n_j falls within the range [c_i - r_i/2, c_i + r_i/2]
    N = structuralmodel(NicheModel, S, connectance)

    # 3. Extract the Adjacency Matrix
    A = _get_matrix(N)

    # 4. Map back to real species names
    # The original structuralmodel returns nodes named 1, 2, 3...
    # This step ensures the Symbols from your 'df.species' are applied.
    edges = Binary(A)
    nodes = Unipartite(Symbol.(species))
    N = SpeciesInteractionNetworks.SpeciesInteractionNetwork(nodes, edges)
    
    # 5. Simplify and Return
    # simplify() ensures there are no isolated components or redundant structures 
    # if required by the package logic.
    return simplify(N)
end